import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Providers } from '../components/Providers';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export  function ServerMenu() {
  return (
    <aside className="w-64 border-r border-slate-700 bg-slate-800 p-4">
      <h2 className="mb-4 text-lg font-semibold">Navigation</h2>
      <nav className="space-y-2 text-sm">
        <Link
          href="/intro"
          className="block rounded px-2 py-1 hover:bg-slate-700"
        >
          Intro
        </Link>
        <Link
          href="/admin"
          className="block rounded px-2 py-1 hover:bg-slate-700"
        >
          Admin
        </Link>
        <Link
          href="/contact"
          className="block rounded px-2 py-1 hover:bg-slate-700"
        >
          Contact
        </Link>
        <Link
          href="/dashboard"
          className="block rounded px-2 py-1 hover:bg-slate-700"
        >
          Dashboard
        </Link>
        <Link
          href="/dashboard2"
          className="block rounded px-2 py-1 hover:bg-slate-700"
        >
          Dashboard2
        </Link>
        <Link
          href="/movies"
          className="block rounded px-2 py-1 hover:bg-slate-700"
        >
          Movies
        </Link>
        <Link
          href="/posts"
          className="block rounded px-2 py-1 hover:bg-slate-700"
        >
          Posts
        </Link>
        <Link
          href="/products"
          className="block rounded px-2 py-1 hover:bg-slate-700"
        >
          Products
        </Link>
        <Link
          href="/recipes"
          className="block rounded px-2 py-1 hover:bg-slate-700"
        >
          Recipes
        </Link>
        <Link
          href="/selector"
          className="block rounded px-2 py-1 hover:bg-slate-700"
        >
          Selector
        </Link>
        <Link
          href="/task/context"
          className="block rounded px-2 py-1 hover:bg-slate-700"
        >
          Task (Context)
        </Link>
        <Link
          href="/task/zustand"
          className="block rounded px-2 py-1 hover:bg-slate-700"
        >
          Task (Zustand)
        </Link>
        <Link
          href="/user/code"
          className="block rounded px-2 py-1 hover:bg-slate-700"
        >
          User (code)
        </Link>
        <Link
          href="/user/signin"
          className="block rounded px-2 py-1 hover:bg-slate-700"
        >
          User (signin)
        </Link>
        <Link
          href="/user/signup"
          className="block rounded px-2 py-1 hover:bg-slate-700"
        >
          User (signup)
        </Link>
        <Link
          href="/products/1"
          className="block rounded px-2 py-1 hover:bg-slate-700"
        >
          Product (example)
        </Link>
        <Link
          href="/sockets/1"
          className="block rounded px-2 py-1 hover:bg-slate-700"
        >
          Socket 1
        </Link>
        <Link
          href="/sockets/2"
          className="block rounded px-2 py-1 hover:bg-slate-700"
        >
          Socket 2
        </Link>
      </nav>
    </aside>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen bg-slate-900 text-slate-100">
          <ServerMenu />
          <Providers>
            <main className="flex-1 bg-transparent p-6">{children}</main>
          </Providers>
        </div>
      </body>
    </html>
  );
}
